NEVISACCESSAPP-5980: Dismiss keyboard when tapping outside text fields
nevissecurity/nevis-mobile-authentication-sdk-example-app-flutter pull request #43
Opened 2024-07-02 13:58 UTC by balazs-gerlei

2024-07-02 14:29 UTC, tamas-toth requested changes

2024-07-02 14:40 UTC, balazs-gerlei commented on lib/ui/screens/auth_cloud_api_registration/auth_cloud_api_registration_screen.dart
> +          onTapOutside: (event) {
Fixed via rebasing.

2024-07-03 06:15 UTC, laszlo-domonkos approved these changes

2024-07-03 06:43 UTC, tamas-toth approved these changes

2024-07-03 14:59 UTC, merged