NEVISACCESSAPP-6212: update gh actions
nevissecurity/nevis-mobile-authentication-sdk-example-app-flutter pull request #54
Opened 2024-10-04 14:28 UTC by daniel-toth-leeder

2024-10-04 14:34 UTC, tamas-toth requested changes

2024-10-04 14:34 UTC, tamas-toth commented on android/app/build.gradle
> +    debugImplementation 'ch.nevis:nevis-mobile-authentication-sdk-android-debug:3.8.+'
🔧 Please do not merge this into main, it is still unreleased :)

2024-10-04 14:34 UTC, tamas-toth commented on ios/Podfile
> +	pod 'NevisMobileAuthentication', '~> 3.8.0', :configurations => ['Release']
🔧 Please do not merge this into main, it is still unreleased :)

2024-10-04 14:34 UTC, tamas-toth commented on pubspec.yaml
> +version: 3.8.0+1
🔧 Please do not merge this into main, it is still unreleased :)

2024-10-04 14:34 UTC, tamas-toth commented on pubspec.yaml
> +  nevis_mobile_authentication_sdk: '>=3.8.0 <3.9.0'
🔧 Please do not merge this into main, it is still unreleased :)

2024-10-07 09:02 UTC, viktor-gulyas approved these changes

2024-10-08 13:04 UTC, merged